-- This is a sample migration.
create table layoffs(
  id bigint generated by default as identity primary key,
  company_name varchar not null,
  company_country varchar not null,
  company_market varchar not null,
  happened_at date not null,
  reported_at date not null,
  confirmed_at date not null,
  amount_affected int not null
);

---- create above / drop below ----
drop table layoffs;